Repository webpack-contrib/compression-webpack-plugin, pull requests merged in 2018-02, with the labels that each got.

#100 fix(index): `tapable` deprecation warnings (`webpack >= v4.0.0`)
  src/index.js
Labels: pr_action: Review, priority: 3 (required), semver: Patch, severity: 4 (inconvenient), type: Bug

#101 fix(package): add `webpack >= 4` (`peerDependencies`)
  package.json
Labels: priority: 4 (important), semver: Patch, severity: 4 (inconvenient), status: Pending, type: Bug

#98 perf: use `neo-async` instead `async`
  package-lock.json
  package.json
  src/index.js
Labels: pr_action: Review, priority: 5 (nice to have), semver: Patch, type: Perf
